[workspace]
resolver = "3"
members = ["ceraunus", "data", "trading-core"]

[workspace.dependencies]
serde = {version = "1.0.228", features = ["derive"]}
tokio = {version = "1.48", features = ["full"]}
reqwest = { version = "0.12.25"}
rust_decimal ={ version = "1.39", features = ["macros", "serde"]}
tracing = { version = "0.1.43" }
uuid = { version = "1.19.0", features=["v4"]}
derive_more = { version = "2.1.0", features = ["full"]}
chrono = {version = "0.4.42"}