[package]
name = "ceraunus"
version = "0.1.0"
edition = "2024"

[dependencies]
trading-core = {path = "../trading-core"}
data = {path = "../data"}

tokio = {workspace = true}
reqwest = { workspace =  true}
rust_decimal = { workspace =  true}

openssl = {workspace = true, features = ["vendored"]}