[package]
name = "trading-core"
version = "0.1.0"
edition = "2024"

[dependencies]
data = {path = "../data"}
rust_decimal = { workspace = true , features = ["macros", "serde"]}
tokio = { workspace = true, features = ["full"] }
chrono = {workspace = true}

